spring.application.name=Backend

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d7itjs1j2pic73b2s8cg-a.oregon-postgres.render.com:5432/devices_4wj1?sslmode=require}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:deviceuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ttC7skWp4uEckY0E3nQmha2TO98MrBvz}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000
#spring.mail.username=nhatnd2701@gmail.com
#spring.mail.password=amsi oxhn rcwj ocjo
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
app.jwt.secret=backend-secret-key-backend-secret-key-2026
app.jwt.expiration=86400000