spring.application.name=Backend

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-d8j1m867r5hc73dd8n1g-a.oregon-postgres.render.com:5432/device_36gn}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:device_36gn_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:TPjjEfTuRTfcOVAnPklsr4IO9vbxCCPY}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# MAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=nhatnd2701@gmail.com
spring.mail.password=duoanwhdckjhxlaz
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false

spring.mail.properties.mail.smtp.connectiontimeout=10000
spring.mail.properties.mail.smtp.timeout=10000
spring.mail.properties.mail.smtp.writetimeout=10000

# JWT
app.jwt.secret=backend-secret-key-backend-secret-key-2026
app.jwt.expiration=86400000